version = 1
SPDX-PackageName = "iron"
SPDX-PackageSupplier = "Advanced Micro Devices, Inc."
SPDX-PackageDownloadLocation = "https://github.com/AARInternal/ironclad"

[[annotations]]
path = "iron/applications/llama_3.2_1b/prompt.txt"
precedence = "closest"
SPDX-FileCopyrightText = "Public Domain"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "iron/applications/transformer_layer/study/block/removed_cases.csv",
    "iron/applications/transformer_layer/study/end_to_end/hybrid_candidates.json",
    "iron/applications/transformer_layer/study/end_to_end/offload_candidates.json",
    "iron/applications/transformer_layer/study/end_to_end/runlist_candidates.json",
    "iron/applications/transformer_layer/study/end_to_end/runlist_removed_candidates.csv",
]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved."
SPDX-License-Identifier = "Apache-2.0"
