# SPDX-FileCopyrightText: Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

TOPOLOGY_PLACEMENTS = {
    (12, 64, 64, 32, 64, 96, 1, 1, 8, 1, 1, 3072): {
        "compute_tiles": {
            "qk": (0, 2),
            "softmax": (0, 3),
            "pv": (0, 4),
            "o_proj": (0, 5),
            "ln1": (1, 5),
            "ffn_up": (5, 5),
            "ffn_down": (6, 5),
            "ln2": (7, 5),
        },
        "mem_tiles": {
            "q": 0,
            "k": 1,
            "v": 2,
            "w_o": 3,
            "o_proj_acc": 4,
            "b_down": 4,
            "ln2_replay": 4,
            "ln1_replay": 5,
            "b_up": 5,
            "ffn_down_acc": 6,
            "ln1_stage": 6,
            "residual": 7,
            "ffn_residual": 7,
            "output": 7,
        },
        "shim_tiles": {
            "q": 0,
            "k": 1,
            "v": 2,
            "w_o": 3,
            "b_down": 4,
            "b_up": 5,
            "ln1_stage": 6,
            "residual": 7,
            "output": 7,
        },
    },
    (12, 128, 64, 32, 64, 96, 1, 1, 8, 1, 1, 3072): {
        "compute_tiles": {
            "qk": (0, 2),
            "softmax": (0, 3),
            "pv": (0, 4),
            "o_proj": (0, 5),
            "ln1": (1, 5),
            "ffn_up": (5, 5),
            "ffn_down": (6, 5),
            "ln2": (7, 5),
        },
        "mem_tiles": {
            "q": 0,
            "k": 1,
            "v": 2,
            "w_o": 3,
            "o_proj_acc": 4,
            "b_down": 4,
            "ln2_replay": 4,
            "ln1_replay": 5,
            "b_up": 5,
            "ffn_down_acc": 6,
            "ln1_stage": 6,
            "residual": 7,
            "ffn_residual": 7,
            "output": 7,
        },
        "shim_tiles": {
            "q": 0,
            "k": 1,
            "v": 2,
            "w_o": 3,
            "b_down": 4,
            "b_up": 5,
            "ln1_stage": 6,
            "residual": 7,
            "output": 7,
        },
    },
    (12, 256, 64, 32, 64, 96, 1, 1, 8, 1, 1, 3072): {
        "compute_tiles": {
            "qk": (0, 2),
            "softmax": (0, 3),
            "pv": (0, 4),
            "o_proj": (0, 5),
            "ln1": (1, 5),
            "ffn_up": (5, 5),
            "ffn_down": (6, 5),
            "ln2": (7, 5),
        },
        "mem_tiles": {
            "q": 0,
            "k": 1,
            "v": 2,
            "w_o": 3,
            "o_proj_acc": 4,
            "b_down": 4,
            "ln2_replay": 4,
            "ln1_replay": 5,
            "b_up": 5,
            "ffn_down_acc": 6,
            "ln1_stage": 6,
            "residual": 7,
            "ffn_residual": 7,
            "output": 7,
        },
        "shim_tiles": {
            "q": 0,
            "k": 1,
            "v": 2,
            "w_o": 3,
            "b_down": 4,
            "b_up": 5,
            "ln1_stage": 6,
            "residual": 7,
            "output": 7,
        },
    },
    (1, 64, 64, 32, 64, 32, 1, 1, 2, 1, 1, 96): {
        "compute_tiles": {
            "qk": (0, 2),
            "softmax": (0, 3),
            "pv": (0, 4),
            "o_proj": (0, 5),
            "ln1": (1, 5),
            "ffn_up": (5, 5),
            "ffn_down": (6, 5),
            "ln2": (7, 5),
        },
        "mem_tiles": {
            "q": 0,
            "k": 1,
            "v": 2,
            "w_o": 3,
            "o_proj_acc": 4,
            "b_down": 4,
            "ln2_replay": 4,
            "ln1_replay": 5,
            "b_up": 5,
            "ffn_down_acc": 6,
            "ln1_stage": 6,
            "residual": 7,
            "ffn_residual": 7,
            "output": 7,
        },
        "shim_tiles": {
            "q": 0,
            "k": 1,
            "v": 2,
            "w_o": 3,
            "b_down": 4,
            "b_up": 5,
            "ln1_stage": 6,
            "residual": 7,
            "output": 7,
        },
    },
}

SUPPORTED_ENCODER_PIPELINE_TOPOLOGIES = frozenset(TOPOLOGY_PLACEMENTS)
